server:
  port: 8080

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: coupon-service
          uri: lb://COUPON-SERVICE
          predicates:
            - Path=/coupon/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
