server:
  port: 8080

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: gift-card-service
          uri: lb://GIFT-CARD-SERVICE
          predicates:
            - Path=/gift-card/**
          filters:
            - name: AuthorizationFilter
              args:
                url-whitelist:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - name: AuthorizationFilter
              args:
                url-whitelist:
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - name: AuthorizationFilter
              args:
                url-whitelist:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - name: AuthorizationFilter
              args:
                url-whitelist:

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  access-secret: qufgpsmsqkarPwjfdlwlskrsmksamfdlkmfoseifjiuashnfiuasdnbfiuasdnbfioansiefounasfiuenasifunsdaioufnasoieufnoaisuenfoiuasndfoiuanseoifunas
